version: '3.1'

services:
  ###
  # MongoDB
  ###
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    container_name: mainflux-mongodb
    command: --smallfiles --nojournal
    networks:
      - mainflux

  ###
  # Redis
  ###
  redis:
    image: redis:alpine
    container_name: mainflux-redis
    ports:
      - "6379:6379"
    networks:
      - mainflux
      - lora

  ###
  # NATS
  ###
  nats:
    image: nats:latest
    container_name: mainflux-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - mainflux

  ###
  # Mainflux MQTT Broker
  ###
  mainflux-mqtt:
    image: mainflux/mainflux-mqtt:latest
    container_name: mainflux-mqtt
    ports:
      - "1883:1883"
    networks:
      - mainflux

  ###
  # Mainflux Core Server
  ###
  mainflux-core:
    image: mainflux/mainflux-core:latest
    container_name: mainflux-core
    ports:
      - "7070:7070"
    networks:
- mainflux
